# Generated by Django 3.2.7 on 2022-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Are you an agent?', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Are you looking to Buy a Property?', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Are you looking to Sell a Property?', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Real Estate License'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='top_agent',
            field=models.BooleanField(default=False, help_text='Are you looking to Buy a Property?', verbose_name='Top Agent'),
        ),
    ]
